name: blood_group_app
channels:
  - defaults
dependencies:
  - abseil-cpp=20211102.0=hd77b12b_0
  - absl-py=2.1.0=py39haa95532_0
  - aiodns=3.5.0=py39haa95532_0
  - aiohappyeyeballs=2.6.1=py39haa95532_0
  - aiohttp=3.12.15=py39h02ab6af_0
  - aiosignal=1.4.0=py39haa95532_0
  - astunparse=1.6.3=py_0
  - async-timeout=5.0.1=py39haa95532_0
  - attrs=25.4.0=py39haa95532_1
  - blas=1.0=mkl
  - blinker=1.9.0=py39haa95532_0
  - brotlicffi=1.0.9.2=py39h885b0b7_2
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.12.2=haa95532_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2025.10.5=py39haa95532_0
  - cffi=2.0.0=py39h02ab6af_0
  - charset-normalizer=3.4.4=py39haa95532_0
  - click=8.1.8=py39haa95532_0
  - colorama=0.4.6=py39haa95532_0
  - contourpy=1.2.1=py39h214f63a_1
  - cryptography=46.0.2=py39h114bc41_0
  - cudatoolkit=11.3.1=h59b6b97_2
  - cudnn=8.2.1=cuda11.3_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - eigen=5.0.1=h3ba6905_0
  - expat=2.7.3=h885b0b7_4
  - ffmpeg=4.2.2=he774522_0
  - flask=3.1.2=py39haa95532_0
  - flask-cors=6.0.1=py39haa95532_0
  - flatbuffers=25.2.10=hbdc3ed3_0
  - fonttools=4.60.1=py39h02ab6af_0
  - freetype=2.13.3=h0620614_0
  - frozenlist=1.8.0=py39h885b0b7_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.2=h7edc060_0
  - glib=2.84.4=h60240c0_0
  - glib-tools=2.84.4=h3823947_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.48.2=hf108199_0
  - grpcio=1.48.2=py39hf108199_0
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - h5py=3.12.1=py39h3b2c811_0
  - hdf5=1.12.1=h51c971a_3
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.11=py39haa95532_0
  - importlib-metadata=8.5.0=py39haa95532_0
  - importlib_resources=6.5.2=py39haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - itsdangerous=2.2.0=py39haa95532_0
  - jinja2=3.1.6=py39haa95532_0
  - joblib=1.5.2=py39haa95532_0
  - jpeg=9f=ha349fce_0
  - kiwisolver=1.4.4=py39hd77b12b_0
  - krb5=1.20.1=h5b6d351_1
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libclang13=14.0.6=default_h8e68704_2
  - libcurl=8.14.1=ha9f67de_0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libiconv=1.16=h2bbff1b_3
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.50=h46444df_0
  - libpq=12.15=hb652d5d_1
  - libprotobuf=3.20.3=h23ce68f_0
  - libssh2=1.10.0=hcd4344a_2
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.10.4=h0ad7f3c_2
  - libxslt=1.1.37=h2bbff1b_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown=3.8=py39haa95532_0
  - markupsafe=3.0.2=py39h827c3e9_0
  - matplotlib=3.9.2=py39haa95532_1
  - matplotlib-base=3.9.2=py39he19b0ae_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h827c3e9_2
  - mkl_fft=1.3.11=py39h827c3e9_0
  - mkl_random=1.2.8=py39hc64d2fc_0
  - multidict=6.7.0=py39h02ab6af_0
  - numpy=1.26.4=py39h055cbcc_0
  - numpy-base=1.26.4=py39h65a83cf_0
  - oauthlib=3.3.1=py39haa95532_0
  - opencv=4.6.0=py39ha36de5b_5
  - openjpeg=2.5.2=hae555c5_0
  - openssl=1.1.1w=h2bbff1b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=25.0=py39haa95532_1
  - pcre2=10.46=h5740b90_0
  - pip=25.3=pyhc872135_0
  - ply=3.11=py39haa95532_0
  - propcache=0.3.1=py39h827c3e9_0
  - protobuf=3.20.3=py39hd77b12b_0
  - pyasn1=0.6.1=py39haa95532_0
  - pyasn1-modules=0.4.2=py39haa95532_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycares=4.10.0=py39he29e43d_0
  - pycparser=2.23=py39haa95532_0
  - pyparsing=3.2.0=py39haa95532_0
  - pyqt=5.15.10=py39h5da7b33_1
  - pyqt5-sip=12.13.0=py39h827c3e9_1
  - pysocks=1.7.1=py39haa95532_1
  - python=3.9.18=h6244533_0
  - python-dateutil=2.9.0post0=py39haa95532_2
  - python-flatbuffers=24.3.25=py39haa95532_0
  - qt-main=5.15.2=h6072711_9
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtwebkit=5.212=h2bbfb41_5
  - re2=2022.04.01=hd77b12b_0
  - requests=2.32.5=py39haa95532_0
  - requests-oauthlib=2.0.0=py39haa95532_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=1.6.1=py39h585ebfc_0
  - scipy=1.13.1=py39h8640f81_1
  - setuptools=80.9.0=py39haa95532_0
  - sip=6.7.12=py39h5da7b33_1
  - six=1.17.0=py39haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.51.0=hda9a48d_0
  - tbb=2021.8.0=h59b6b97_0
  - tensorboard-plugin-wit=1.8.1=py39haa95532_0
  - termcolor=2.1.0=py39haa95532_0
  - threadpoolctl=3.5.0=py39h9909e9c_0
  - tk=8.6.15=hf199647_0
  - tomli=2.2.1=py39haa95532_0
  - tornado=6.5.1=py39h827c3e9_0
  - typing-extensions=4.15.0=py39haa95532_0
  - typing_extensions=4.15.0=py39haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py39haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - werkzeug=3.1.3=py39haa95532_0
  - wheel=0.45.1=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_1
  - winloop=0.2.2=py39h913537a_0
  - xz=5.6.4=h4754444_1
  - yarl=1.18.0=py39h827c3e9_0
  - zipp=3.21.0=py39haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - bcrypt==5.0.0
      - flask-bcrypt==1.0.1
      - flask-sqlalchemy==3.1.1
      - google-auth==2.48.0
      - google-auth-oauthlib==1.2.4
      - greenlet==3.2.4
      - keras==2.15.0
      - libclang==18.1.1
      - ml-dtypes==0.2.0
      - opencv-python-headless==4.12.0.88
      - pandas==2.3.3
      - pillow==11.3.0
      - psycopg2==2.9.11
      - psycopg2-binary==2.9.11
      - pytz==2025.2
      - seaborn==0.13.2
      - sqlalchemy==2.0.45
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-intel==2.15.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - tzdata==2025.3
      - wrapt==1.14.2
prefix: C:\Users\Admin\anaconda3\envs\blood_group_app
